### ISSUE TITLE
failed to work with CF Dev (x509: certificate signed by unknown authority)

### ISSUE THREAD

**Issue by drnic** [govau/cf-report-users#2]
```
$ cf dev start
$ cf login -a https://api.dev.cfdev.sh --skip-ssl-validation -u user -p pass
$ cf report-users

2019/04/29 09:39:32 GET https://api.dev.cfdev.sh/v2/organizations
2019/04/29 09:39:32 Get https://api.dev.cfdev.sh/v2/organizations: x509: certificate signed by unknown authority
```

Want a PR to allow skipping SSL validation if `~/.cf/config.json` has `SSLDisabled: true`?

**Comment by aeijdenberg** [comment]
Sorry to miss the notification - looks like when I created this repo, I wasn't actually watching it. ;)

We could add - though the point of this plugin is to audit usage of real environments, so I wouldn't have thought it would be terribly useful?

**Comment by bala151187** [comment]
You can use mine . i have added the feature to skip self signed certificates 
https://github.com/bala151187/cf-report-users

**Comment by drnic** [comment]
Thanks @bala151187 for #1 
/cc @aeijdenberg

**Comment by aeijdenberg** [comment]
Fixed in https://github.com/govau/cf-report-users/commit/da1135c83a90f099b8916fe8142ce22044c719d2 (although tbh I didn't test again in a self-signed env, so let me know if it didn't work for any reason).

Thanks @bala151187 and @drnic
